name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-files:
    name: Lint readme file
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint readme file
        uses: avto-dev/markdown-lint@v1
        with:
          #rules: '/lint/rules/changelog.js'
          #config: '/lint/config/changelog.yml'
          args: '*.md'

      - name: Lint python files
        uses: quentinguidee/pep8-action@v1
        with:
          arguments: '--max-line-length=120'
