name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-files:
    name: Lint + Codestyle
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint readme file
        uses: avto-dev/markdown-lint@v1
        with:
          args: '*.md'
          ignore: 'CHANGELOG.md'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --max-complexity=10 --max-line-length=120 --statistics

      - name: Lint python files
        uses: quentinguidee/pep8-action@v1
        with:
          arguments: '--max-line-length=120'

  deletion-test:
    name: Deletion-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Copy config
        run: |
          cp resources/config-tst.yml src/config.yml

      - name: Create tmp files
        run: |
          mkdir /tmp/rob-test-files
          touch /tmp/rob-test-files/db-backup.00.sql
          touch /tmp/rob-test-files/db-backup.01.sql
          touch /tmp/rob-test-files/db-backup.02.sql
          touch /tmp/rob-test-files/db-backup.03.sql
          touch /tmp/rob-test-files/db-backup.04.sql
          touch /tmp/rob-test-files/db-backup.05.sql
          touch /tmp/rob-test-files/db-backup.06.sql
          touch /tmp/rob-test-files/db-backup.07.sql
          touch /tmp/rob-test-files/db-backup.08.sql
          touch /tmp/rob-test-files/db-backup.09.sql
          touch /tmp/rob-test-files/db-backup.10.sql
          touch /tmp/rob-test-files/db-backup.11.sql
          touch /tmp/rob-test-files/db-backup.12.sql

      - name: Show files
        run: |
          ls -la /tmp/rob-test-files
