name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-files:
    name: Lint + Codestyle
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint readme file
        uses: avto-dev/markdown-lint@v1
        with:
          args: '*.md'
          ignore: 'CHANGELOG.md'

      - name: Lint python files
        uses: quentinguidee/pep8-action@v1
        with:
          arguments: '--max-line-length=120'
